name: Deploy FastAPI to Koyeb

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to Koyeb
      - name: Deploy to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $KOYEB_API_TOKEN" \
            -X POST https://app.koyeb.com/v1/apps/64q9gs1wgg6pjjs1905vlo009bq3itgkvz5qyq9mdx8oyjhoj2ewqkm5yw5rmujp/deployments
